"""core schema

Revision ID: 63319fb33306
Revises:
Create Date: 2026-09-09 23:32:39.475283

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "63319fb33306"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "airlines",
        sa.Column("iata", sa.String(length=2), nullable=False),
        sa.Column("icao", sa.String(length=3), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("iata"),
    )
    op.create_table(
        "airports",
        sa.Column("iata", sa.String(length=3), nullable=False),
        sa.Column("icao", sa.String(length=4), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("iata"),
    )
    op.create_index(op.f("ix_airports_country"), "airports", ["country"], unique=False)
    op.create_table(
        "routes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("airline_iata", sa.String(length=2), nullable=False),
        sa.Column("src_iata", sa.String(length=3), nullable=False),
        sa.Column("dst_iata", sa.String(length=3), nullable=False),
        sa.Column("equipment", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("airline_iata", "src_iata", "dst_iata", name="uq_route"),
    )
    op.create_index(op.f("ix_routes_airline_iata"), "routes", ["airline_iata"], unique=False)
    op.create_index("ix_routes_src_dst", "routes", ["src_iata", "dst_iata"], unique=False)
    op.create_table(
        "security_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_email", sa.String(length=320), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("method", sa.String(length=8), nullable=True),
        sa.Column("path", sa.String(length=200), nullable=True),
        sa.Column("resource_type", sa.String(length=32), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("decision", sa.String(length=16), nullable=True),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_secevent_occurred_desc",
        "security_events",
        [sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_secevent_type_occurred", "security_events", ["event_type", "occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_security_events_actor_user_id"), "security_events", ["actor_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_security_events_event_type"), "security_events", ["event_type"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mfa_secret_enc", sa.LargeBinary(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "flights",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("flight_no", sa.String(length=8), nullable=False),
        sa.Column("airline_iata", sa.String(length=2), nullable=False),
        sa.Column("src_iata", sa.String(length=3), nullable=False),
        sa.Column("dst_iata", sa.String(length=3), nullable=False),
        sa.Column("depart_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("arrive_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("aircraft_type", sa.String(length=8), nullable=False),
        sa.Column("base_fare", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.CheckConstraint("arrive_at > depart_at", name="ck_flight_times"),
        sa.CheckConstraint("base_fare >= 0", name="ck_flight_fare_nonneg"),
        sa.ForeignKeyConstraint(["airline_iata"], ["airlines.iata"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["dst_iata"], ["airports.iata"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["src_iata"], ["airports.iata"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("airline_iata", "flight_no", "depart_at", name="uq_flight_instance"),
    )
    op.create_index(
        "ix_flights_search", "flights", ["src_iata", "dst_iata", "depart_at"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["refresh_tokens.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "bookings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ref", sa.String(length=6), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("flight_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("total_amount >= 0", name="ck_booking_total_nonneg"),
        sa.ForeignKeyConstraint(["flight_id"], ["flights.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ref"),
    )
    op.create_index("ix_bookings_user_created", "bookings", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_bookings_user_id"), "bookings", ["user_id"], unique=False)
    op.create_table(
        "fare_classes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("flight_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("cabin", sa.String(length=16), nullable=False),
        sa.Column("multiplier", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("seats_total", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["flight_id"], ["flights.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flight_id", "code", name="uq_fare_class"),
    )
    op.create_index(op.f("ix_fare_classes_flight_id"), "fare_classes", ["flight_id"], unique=False)
    op.create_table(
        "booking_audit",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("from_state", sa.String(length=24), nullable=True),
        sa.Column("to_state", sa.String(length=24), nullable=True),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_id", "seq", name="uq_audit_seq"),
    )
    op.create_index("ix_audit_booking_seq", "booking_audit", ["booking_id", "seq"], unique=False)
    op.create_index("ix_audit_occurred", "booking_audit", ["occurred_at"], unique=False)
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("endpoint", sa.String(length=80), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("booking_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("key", "user_id"),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_ref", sa.String(length=64), nullable=True),
        sa.Column("card_token", sa.String(length=64), nullable=False),
        sa.Column("card_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("card_last4", sa.String(length=4), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("failure_code", sa.String(length=48), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payments_booking_id"), "payments", ["booking_id"], unique=False)
    op.create_index(
        op.f("ix_payments_card_fingerprint"), "payments", ["card_fingerprint"], unique=False
    )
    op.create_table(
        "seat_inventory",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("flight_id", sa.UUID(), nullable=False),
        sa.Column("seat_no", sa.String(length=4), nullable=False),
        sa.Column("row_no", sa.SmallInteger(), nullable=False),
        sa.Column("seat_letter", sa.String(length=1), nullable=False),
        sa.Column("cabin", sa.String(length=16), nullable=False),
        sa.Column("fare_class_id", sa.UUID(), nullable=False),
        sa.Column("is_exit_row", sa.Boolean(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(length=12), server_default="available", nullable=False),
        sa.Column("held_by_user_id", sa.UUID(), nullable=True),
        sa.Column("hold_id", sa.UUID(), nullable=True),
        sa.Column("hold_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("booking_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "(status <> 'booked') OR (booking_id IS NOT NULL)", name="ck_booked_seat_has_booking"
        ),
        sa.CheckConstraint(
            "(status <> 'held') OR (held_by_user_id IS NOT NULL AND hold_expires_at IS NOT NULL AND hold_id IS NOT NULL)",
            name="ck_held_seat_has_holder",
        ),
        sa.CheckConstraint("status IN ('available','held','booked')", name="ck_seat_status"),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["fare_class_id"], ["fare_classes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["flight_id"], ["flights.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["held_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flight_id", "seat_no", name="uq_seat_per_flight"),
    )
    op.create_index(
        "ix_seat_booking",
        "seat_inventory",
        ["booking_id"],
        unique=False,
        postgresql_where=sa.text("booking_id IS NOT NULL"),
    )
    op.create_index(
        "ix_seat_flight_status", "seat_inventory", ["flight_id", "status"], unique=False
    )
    op.create_index(
        "ix_seat_hold_expiry",
        "seat_inventory",
        ["hold_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'held'"),
    )
    op.create_index(
        "ix_seat_hold_id",
        "seat_inventory",
        ["hold_id"],
        unique=False,
        postgresql_where=sa.text("hold_id IS NOT NULL"),
    )
    op.create_table(
        "booking_passengers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("given_name", sa.String(length=100), nullable=False),
        sa.Column("family_name", sa.String(length=100), nullable=False),
        sa.Column("dob_enc", sa.LargeBinary(), nullable=True),
        sa.Column("passport_enc", sa.LargeBinary(), nullable=True),
        sa.Column("passport_last4", sa.String(length=4), nullable=True),
        sa.Column("seat_inventory_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["seat_inventory_id"], ["seat_inventory.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_booking_passengers_booking_id"), "booking_passengers", ["booking_id"], unique=False
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("passenger_id", sa.UUID(), nullable=False),
        sa.Column("seat_inventory_id", sa.UUID(), nullable=False),
        sa.Column("e_ticket_no", sa.String(length=16), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["passenger_id"], ["booking_passengers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["seat_inventory_id"], ["seat_inventory.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("e_ticket_no"),
        sa.UniqueConstraint("passenger_id", name="uq_ticket_per_passenger"),
        sa.UniqueConstraint("seat_inventory_id", name="uq_ticket_per_seat"),
    )
    op.create_index(op.f("ix_tickets_booking_id"), "tickets", ["booking_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tickets_booking_id"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_booking_passengers_booking_id"), table_name="booking_passengers")
    op.drop_table("booking_passengers")
    op.drop_index(
        "ix_seat_hold_id",
        table_name="seat_inventory",
        postgresql_where=sa.text("hold_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_seat_hold_expiry",
        table_name="seat_inventory",
        postgresql_where=sa.text("status = 'held'"),
    )
    op.drop_index("ix_seat_flight_status", table_name="seat_inventory")
    op.drop_index(
        "ix_seat_booking",
        table_name="seat_inventory",
        postgresql_where=sa.text("booking_id IS NOT NULL"),
    )
    op.drop_table("seat_inventory")
    op.drop_index(op.f("ix_payments_card_fingerprint"), table_name="payments")
    op.drop_index(op.f("ix_payments_booking_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_table("idempotency_keys")
    op.drop_index("ix_audit_occurred", table_name="booking_audit")
    op.drop_index("ix_audit_booking_seq", table_name="booking_audit")
    op.drop_table("booking_audit")
    op.drop_index(op.f("ix_fare_classes_flight_id"), table_name="fare_classes")
    op.drop_table("fare_classes")
    op.drop_index(op.f("ix_bookings_user_id"), table_name="bookings")
    op.drop_index("ix_bookings_user_created", table_name="bookings")
    op.drop_table("bookings")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_flights_search", table_name="flights")
    op.drop_table("flights")
    op.drop_table("users")
    op.drop_index(op.f("ix_security_events_event_type"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_actor_user_id"), table_name="security_events")
    op.drop_index("ix_secevent_type_occurred", table_name="security_events")
    op.drop_index("ix_secevent_occurred_desc", table_name="security_events")
    op.drop_table("security_events")
    op.drop_index("ix_routes_src_dst", table_name="routes")
    op.drop_index(op.f("ix_routes_airline_iata"), table_name="routes")
    op.drop_table("routes")
    op.drop_index(op.f("ix_airports_country"), table_name="airports")
    op.drop_table("airports")
    op.drop_table("airlines")
    # ### end Alembic commands ###
