"""tickets: void instead of delete; partial unique indexes

Revision ID: b5d76c6c1ea5
Revises: 0002_append_only
Create Date: 2026-09-10 09:03:12.753623

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b5d76c6c1ea5"
down_revision: str | None = "0002_append_only"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f("uq_ticket_per_passenger"), "tickets", type_="unique")
    op.drop_constraint(op.f("uq_ticket_per_seat"), "tickets", type_="unique")
    op.create_index(
        "uq_ticket_live_per_passenger",
        "tickets",
        ["passenger_id"],
        unique=True,
        postgresql_where=sa.text("voided_at IS NULL"),
    )
    op.create_index(
        "uq_ticket_live_per_seat",
        "tickets",
        ["seat_inventory_id"],
        unique=True,
        postgresql_where=sa.text("voided_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_ticket_live_per_seat",
        table_name="tickets",
        postgresql_where=sa.text("voided_at IS NULL"),
    )
    op.drop_index(
        "uq_ticket_live_per_passenger",
        table_name="tickets",
        postgresql_where=sa.text("voided_at IS NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_ticket_per_seat"),
        "tickets",
        ["seat_inventory_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_ticket_per_passenger"),
        "tickets",
        ["passenger_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("tickets", "voided_at")
    # ### end Alembic commands ###
